package com.servicedesk.incident;

public enum IncidentEventType {
    CREATED,
    STATUS_CHANGED,
    COMMENT_ADDED,
    ASSIGNED,
    REASSIGNED,
    AI_ANALYSIS_COMPLETED,
    AI_ANALYSIS_FAILED,
    REMEDIATION_RECOMMENDED,
    REMEDIATION_APPROVED,
    REMEDIATION_REJECTED,
    REMEDIATION_STARTED,
    REMEDIATION_SUCCEEDED,
    REMEDIATION_FAILED,
    HEALTH_CHECK_PASSED,
    HEALTH_CHECK_FAILED,
    ESCALATED,
    RESOLVED,
    REOPENED
}
